# https://github.com/cushycush/store
stores:
    aerospace:
        target: ~/.config/aerospace
    claude:
        target: ~/.claude
        files:
            - CLAUDE.md
        patterns:
            - scripts/kitty_focus_next_claude.sh
    fzf:
        target: ~/.config
        files:
            - fzf-git.sh
    gh:
        target: ~/.config/gh
    ghostty:
        target: ~/.config/ghostty
    kitty:
        target: ~/.config/kitty
    lazydocker:
        target: ~/.config/lazydocker
    michaelmux:
        target: ~/.local
        patterns:
            - bin/**
            - lib/**
    nvim:
        target: ~/.config/nvim
    sketchybar:
        target: ~/.config/sketchybar
    starship:
        target: ~/.config
        files:
            - starship.toml
    wezterm:
        target: ~/.config/wezterm
    zed:
        target: ~/.config/zed
    zsh:
        target: "~"
        files:
            - .zshrc
            - .zprofile
