-- local capabilities = require('blink.cmp').get_lsp_capabilities()
--
-- -------------------------------------------------------------------------------
-- -------------------------------------------------------------------------------
-- -------------------------------------------------------------------------------
-- vim.lsp.config('pylsp', {
--     -- see above, might want to do this for all lsp, but idt it makes sense for lua
--     root_markers = { '.git' },
--     filetypes = {'python'},
--
--     -- cmd = {"pylsp", "-vvv", "--log-file", "/tmp/lsp.log"},
--     cmd = {"pylsp", ""},
--
--     -- on_attach = on_attach,
--     capabilities = capabilities,
--
--     settings = {
--         pylsp = {
--             configuationSources = { 'flake8' },
--             plugins = {
--                 jedi = {
--                     -- TODO: could be used to import pytest stuff
--                     -- auto_import_modules
--                     -- extra_paths
--                     follow_imports = true,
--                 },
--                 jedi_completion = {
--                     enabled = true,
--                     include_params = true,
--                 },
--                 ruff = {
--                     enabled = true,
--                 },
--                 flake8 = { enabled = false },
--                 pycodestyle = { enabled = false },
--                 mccabe = { enabled = false },
--                 pyflakes = { enabled = false },
--                 black = {
--                     enabled = true,
--                 },
--                 mypy = {
--                     enabled = true,
--                     live_mode = true,
--                 },
--                 -- pylsp_mypy = { enabled = true },
--                 isort = {
--                     enabled = true,
--                 },
--             }
--         }
--     }
-- })
--
-- vim.lsp.enable('pylsp')
--
--
--
-- -------------------------------------------------------------------------------
-- -------------------------------------------------------------------------------
-- -- JSON (formatting by Prettier via conform)
-- vim.lsp.config('jsonls', {
--   capabilities = capabilities,
-- })
-- vim.lsp.enable('jsonls')
--
--
-- -------------------------------------------------------------------------------
-- -------------------------------------------------------------------------------
-- -- YAML
-- vim.lsp.config('yamlls', {
--   capabilities = capabilities,
--   cmd = { "yaml-language-server", "--stdio" },
--   filetypes = { "yaml", "yaml.docker-compose", "yaml.gitlab" },
--   settings = {
--     redhat = {
--       telemetry = {
--         enabled = false
--       }
--     },
--     yaml = {
--       schemas = {
--         -- ["https://json.schemastore.org/github-workflow.json"] = "/.github/workflows/*",
--         -- ["../path/relative/to/file.yml"] = "/.github/workflows/*",
--         -- ["/path/from/root/of/project"] = "/.github/workflows/*",
--       },
--     },
--   }
-- })
--
-- vim.lsp.enable('yamlls')
--
--
--
-- -- OLDER STYLE
--
-- -- A lot of this is from https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua
--
--
-- -- Setup language servers.
-- -- local lspconfig = require('lspconfig')
--
--
-- -- Use LspAttach autocommand to only map the following keys after the language server
-- -- attaches to the current buffer
-- vim.api.nvim_create_autocmd('LspAttach', {
--   group = vim.api.nvim_create_augroup('UserLspConfig', {}),
--   callback = function(event)
--     local opts = { buffer = event.buf }
--     -- Sets the mode, buffer and description for us each time.
--     local map = function(keys, func, desc, mode)
--       mode = mode or 'n'
--       vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
--     end
--
--     -- vim.keymap.set('n', '<leader>wa', vim.lsp.buf.add_workspace_folder, opts)
--     -- vim.keymap.set('n', '<leader>wr', vim.lsp.buf.remove_workspace_folder, opts)
--     -- vim.keymap.set('n', '<leader>wl', function()
--
--     -- Execute a code action, usually your cursor needs to be on top of an error
--     -- or a suggestion from your LSP for this to activate.
--     map('<leader>ca', vim.lsp.buf.code_action, '[C]ode [A]ction', { 'n', 'x' })
--
--   end,
-- })
--
--
--
-- ----------------------------
-- -- Language server setup
-- ----------------------------
--
--
-- -- Lua
-- -- Lua is currently handled by the "lazydev" plugin
--
-- --------------------------------------------------------------------------------
-- -- PYTHON ----------------------------------------------------------------------
-- --------------------------------------------------------------------------------
-- -- lspconfig["basedpyright"].setup({
-- --   capabilities = capabilities,
-- --   settings = {
-- --     basedpyright = {
-- --       typeCheckingMode = "off",
-- --     },
-- --   },
-- -- })
--
-- -- Jedi (installed via pipx)
-- -- require 'lspconfig'.jedi_language_server.setup({
-- --   capabiliites = capabilities,
-- --   follow_imports = true,
-- -- })
--
-- -- Ruff
-- -- https://docs.astral.sh/ruff/editors/setup/#neovim
-- -- NOTE: see link for logging if needed
-- -- require('lspconfig').ruff.setup({
-- --   capabiliites = capabilities,
-- --   init_options = {
-- --     settings = {
-- --       -- Ruff language server settings go here
-- --     }
-- --   }
-- -- })
--
-- -- Handler for both together
-- -- vim.api.nvim_create_autocmd("LspAttach", {
-- --   group = vim.api.nvim_create_augroup('lsp_attach_disable_ruff_hover', { clear = true }),
-- --   callback = function(args)
-- --     local client = vim.lsp.get_client_by_id(args.data.client_id)
-- --     if client == nil then
-- --       return
-- --     end
-- --     if client.name == 'ruff' then
-- --       -- Disable hover in favor of Pyright
-- --       client.server_capabilities.hoverProvider = false
-- --     end
-- --   end,
-- --   desc = 'LSP: Disable hover capability from Ruff',
-- -- })
-- --------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------
